### ISSUE TITLE
Your frontend name is already being used by another frontend

### ISSUE THREAD

**Issue by CiroConsentino** [ParthK117/Emuloader#2]
hi,
I'm the coder of "Emu Loader - Multiple Systems Frontend"... or just "Emu Loader", and I've been working on it since 1997 and updating it till this day.

I wonder if you can change the name of your frontend. I won't change mine because I've been working on it for more than 20 years, and it's well known in the emulation community.

Thank you.
Regards,
Ciro Alfredo Consentino

Emu Loader
http://emuloader.mameworld.info
e-mail: emuloader@gmail.com

**Comment by ParthK117** [comment]
Hey thanks for your comment!

I’ve seen your front end and am a big fan! However, I was of the opinion that my project and yours differ in branding and function significantly enough that it wouldn’t be an issue. I appreciate that you would want to avoid confusion but I hope you understand the amount of work and time that would go into rebranding emuloader, as there are a significant number of images, videos, posts, subreddits etc and I haven’t noticed any discussions where they have been confused. 

I’d prefer that for now, as emuloader does not have a large footprint and is relatively unknown, the name remains as it is and if there becomes instances in which the two are confused I can begin switching over to a new name, as I respect that you’ve been developing Emu Loader for a very long time and wouldn’t want you to change your name.

Would this be okay? Your concern is definitely valid but I don’t see the immediate need for a name change when no one has confused them as of yet. If you’re not happy about this solution don’t hesitate to reply, I want to make sure I can accommodate a veteran emulation community contributor such as yourself.

**Comment by CiroConsentino** [comment]
hi,
if you knew the existence of my project then why use this name ? When I started my project back in 1997 I searched the internet to make sure "Emu Loader" wasn't being used. It's simple and quick. I understand the work involved, been doing it for many years. It's unknown now, wait a few months.
It would be best if the name changed. Trust me when I say, the longer you keep this name, more images, videos and other stuff will be created. Then it will be impossible to rebrand.

I can't force you to rebrand because my frontend, "Emu" "Loader" (two words) is not trademarked (and I don't intend to do it). But in the long run, every time some writes "Emuloader" (some people write it this way either though is wrong), it's usually associated with my project.
I'm not looking for fame or care about publicity, but you're right, I am not happy with your brand approach. I've learned that your project was named "W emuloader" until a couple months ago. Why not keep that ? It's similar name, but not exactly the same.
I've found comments of people already warning about the name might be mixed up with my project.

Please reconsider.
Regards.

**Comment by CiroConsentino** [comment]
Oh, one more issue. If something bad happens to your project, for whatever reason,  it might just bring my project down to the mud with yours.

**Comment by ParthK117** [comment]
Hey again,

As I mentioned earlier I decided that emuloader and Emu Loader were differentiated enough, both in featureset and in branding that no one would reasonably confuse the two. I also have not encountered anyone confusing the two, and would appreciate if you could link the discussions where this took place.

I appreciate that you aren’t forcing me to rebrand, and I understand if you’re not happy about my brand approach. The reason I changed from W Emuloader to emuloader was due to the issues pronouncing the former. I would much rather not waste development time on redesigning images, nor am I presently in a position to make such a large change in a timely manner (I have recently moved and have only a laptop) and so such a change would take months.

However, if you really do not see emuloader and Emu Loader co-existing with the same name, I will defer to you and your experience in the emulation community and begin discussing the feasibility of a name change and subsequent transition with the others involved in the project, though I must reiterate that I do not think it is necessary.

**Comment by CiroConsentino** [comment]
I can see your mind is made up about this. I wonder why you chose to use this name, knowing my frontend existed.
Do whatever you think is best for your project.
If someday you see that it is feasable a name change,  it's appretiated.

Best of luck on your future endeavors.

**Comment by ParthK117** [comment]
Hello again,

I wasn't aware of your front end until after branding was complete for emuloader. I assure you it was not done with any malicious intent.

You may have misunderstood my last comment. I am looking into a name change but I hope you can appreciate that a name change is not a simple name swap on the repository and so a significant amount of legwork has to happen before I can begin the transition (such as thinking of a new name for example).

Thank you for being polite throughout and let me know if you've got any other questions or concerns.

**Comment by CiroConsentino** [comment]
Ok, thanks for listening.
Regards.

**Comment by ParthK117** [comment]
Closing issue, name change will begin when able.
